# Generated by Django 6.0 on 2025-12-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_nombre', models.CharField(max_length=50)),
                ('objeto_categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.categoriaobjeto', verbose_name='relacionado categoria objeto')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ol_cantidad', models.SmallIntegerField()),
                ('ol_estado', models.CharField(choices=[('B', 'Bueno'), ('P', 'Pendiente'), ('M', 'Malo')], max_length=1)),
                ('ol_detalle', models.CharField(max_length=200)),
                ('ol_fecha', models.DateField()),
                ('ol_lugar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.lugar', verbose_name='relacionado lugar')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ant_cant', models.SmallIntegerField()),
                ('ho_ant_estado', models.CharField(choices=[('B', 'Bueno'), ('P', 'Pendiente'), ('M', 'Malo')], max_length=1)),
                ('ho_ant_detalle', models.CharField(max_length=200)),
                ('ho_ant_fecha', models.DateField()),
                ('ho_objeto_lugar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.objetolugar', verbose_name='relacionado objeto lugar')),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='lugar_tipo_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.tipolugar', verbose_name='relacionado tipo lugar'),
        ),
        migrations.CreateModel(
            name='TipoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_marca', models.CharField(max_length=50)),
                ('to_material', models.CharField(max_length=60)),
                ('to_objeto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.objeto', verbose_name='relacionado objeto')),
            ],
        ),
        migrations.AddField(
            model_name='objetolugar',
            name='ol_tipo_objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.tipoobjeto', verbose_name='relacionado tipo objeto'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_nombre', models.CharField(max_length=100)),
                ('lugar_sector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='p_w_pvsa.sector', verbose_name='relacionado sector')),
            ],
        ),
    ]
