# Generated by Django 6.0 on 2026-01-06 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_w_pvsa', '0002_tipolugarobjetotipico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='geom',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='geom',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AreaMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('S', 'Sector'), ('U', 'Ubicación')], max_length=1)),
                ('nombre', models.CharField(max_length=120)),
                ('geometry', models.JSONField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_mapa', to='p_w_pvsa.sector')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_mapa', to='p_w_pvsa.ubicacion')),
            ],
        ),
    ]
